spring:
  application:
    name: ms-books-catalogue

  datasource:
    url: jdbc:h2:mem:catalogue-db;Mode=Mysql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ms-books-catalogue